### ISSUE TITLE
IssueGitHub Nati

### ISSUE THREAD

**Issue by mariaelisaaraya** [mariaelisaaraya/tareasIngeniasAlumnas#153]
Pasar captura de git status y git branch del repositorio local

**Comment by SoleCisnero3** [comment]
profe, no me deja subir imagen. seguí los pasos tal cual, pude clonar el repo, hice la rama y commitie los  cambios, no me sale ningún error y me figura que se subió correctamente pero cuando me meto a tu repo no veo mi archivo.

**Comment by SoleCisnero3** [comment]
![git status](https://github.com/mariaelisaaraya/tareasIngeniasAlumnas/assets/126639371/ed241088-cf7e-4b12-ae34-426669b1bf2f)

asi me aparece cuando quiro subir una captura.

**Comment by mariaelisaaraya** [comment]
Oki, Nati leete los comentarios de esto: https://github.com/mariaelisaaraya/tareasIngeniasAlumnas/pull/150 

y por favor solamente mandame captura de git status y git branch.
